### ISSUE TITLE
CellId

### ISSUE THREAD

**Issue by agga1** [agga1/distributed_simulator#1]
current grid structure:
{%{
   {1, 1} => %Cell{id: 1, state: :empty},
   {1, 2} => %Cell{id: 2, state: :empty},
   {1, 3} => %Cell{id: 3, state: :empty},
...}
 %{
   {1, 1} => %{bottom: {2, 1}, bottom_right: {2, 2}, right: {1, 2}},
   {1, 2} => %{
     bottom: {2, 2},
     bottom_left: {2, 1},
     bottom_right: {2, 3},
     left: {1, 1},
...}
}
meaning: { map(cell-coord => cell struct), map(cell-coord => neighbors }
suggestion:
cell.id unnecessary - should use coords as id
as in xinuk: case class GridCellId(x: Int, y: Int) extends CellId

%{
   {1, 1} => :empty,
   {1, 2} => :empty,
   {1, 3} => :empty,
...}
meaning: { map(cell-id => contents), map(cell-id=> neighbors}
would be sufficient, and promotes more functional approach

Possible problem:
lost information about cell id  while analyzing cell
solution: cells would be anyway always passed by their id

**Comment by sheldak** [comment]
Using coords as id seems to be a good idea. Making Cell struct I was thinking about adding signal (scent) information to it in the future, but now I think we can make another map(coords => scent-info) instead. For now I see no use of that struct so we can even remove it.
